# name: Publish c2patool binaries

# on:
#   push: # Temporary while debugging ...
#   workflow_dispatch:

# jobs:
#   get-latest-tag:
#     name: Get latest c2patool tag
#     runs-on: ubuntu-latest
#     outputs:
#       latest-tag: ${{ steps.get-latest-tag.outputs.tag }}
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: Get latest existing tag
#         uses: actions-ecosystem/action-get-latest-tag@v1
#         id: get-latest-tag
#         with:
#           semver_only: true
#   publish-binaries:
#     name: Publish c2patool binaries
#     runs-on: ${{ matrix.os }}
#     needs: get-latest-tag
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#         rust_version: [stable]
#         experimental: [false]
#         include:
#           - os: macos-latest
#             artifact_name: c2patool_mac.zip
#           - os: ubuntu-latest
#             artifact_name: c2patool_linux.tar.gz
#           - os: windows-latest
#             artifact_name: c2patool_win.zip
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: Install Rust toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: ${{ matrix.rust_version }}
#           components: llvm-tools-preview
#           override: true
#       - name: Cache Rust dependencies
#         uses: Swatinem/rust-cache@v1
#       - name: Run make release
#         run: make release
#       - name: Upload binary to github
#         uses: svenstaro/upload-release-action@v1-release
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: target/${{ matrix.artifact_name }}
#           asset_name: ${{ matrix.artifact_name }}
#           tag: ${{  needs.get-latest-tag.outputs.latest-tag }}
#           overwrite: true
